import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "./styles.module.scss";
import Heading from "@/components/Heading";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Dashboard() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Heading title="Olá 📊" subtitle="confira seu Dashboard." />
        </div>
        <div className={styles.body}><h1>Dashboard</h1></div>
      </main>
    </Layout>
  );
}
